services:
  mongodb:
    image: mongo
    container_name: mongodb_dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  nestjs-app:
    image: codecla-nestjs:v1
    container_name: nestjs-app
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      DATABASE_URL: ${MONGODB_URI}

volumes:
  mongo-data:
